// Author: Antonio Lattanzio - emptyvessel

#pragma once

#include "CoreMinimal.h"
#include "Stats/Stats.h"

DECLARE_STATS_GROUP(TEXT("Box3D"), STATGROUP_Box3D, STATCAT_Advanced);

// Phases. Step is the whole b3World_Step; the rest are its parts.
DECLARE_FLOAT_COUNTER_STAT_EXTERN(TEXT("Step (ms)"), STAT_Box3DStep, STATGROUP_Box3D, BOX3DUNREAL_API);
DECLARE_FLOAT_COUNTER_STAT_EXTERN(TEXT("Broadphase pairs (ms)"), STAT_Box3DPairs, STATGROUP_Box3D, BOX3DUNREAL_API);
DECLARE_FLOAT_COUNTER_STAT_EXTERN(TEXT("Collide (ms)"), STAT_Box3DCollide, STATGROUP_Box3D, BOX3DUNREAL_API);
DECLARE_FLOAT_COUNTER_STAT_EXTERN(TEXT("Solve (ms)"), STAT_Box3DSolve, STATGROUP_Box3D, BOX3DUNREAL_API);
DECLARE_FLOAT_COUNTER_STAT_EXTERN(TEXT("Continuous (ms)"), STAT_Box3DBullets, STATGROUP_Box3D, BOX3DUNREAL_API);
DECLARE_FLOAT_COUNTER_STAT_EXTERN(TEXT("Sensors (ms)"), STAT_Box3DSensors, STATGROUP_Box3D, BOX3DUNREAL_API);

// Our own cost around the sim, which box3d can't see.
DECLARE_CYCLE_STAT_EXTERN(TEXT("Body sync"), STAT_Box3DBodySync, STATGROUP_Box3D, BOX3DUNREAL_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Event dispatch"), STAT_Box3DEvents, STATGROUP_Box3D, BOX3DUNREAL_API);

// Counters.
DECLARE_DWORD_COUNTER_STAT_EXTERN(TEXT("Bodies"), STAT_Box3DBodies, STATGROUP_Box3D, BOX3DUNREAL_API);
DECLARE_DWORD_COUNTER_STAT_EXTERN(TEXT("Shapes"), STAT_Box3DShapes, STATGROUP_Box3D, BOX3DUNREAL_API);
DECLARE_DWORD_COUNTER_STAT_EXTERN(TEXT("Contacts"), STAT_Box3DContacts, STATGROUP_Box3D, BOX3DUNREAL_API);
DECLARE_DWORD_COUNTER_STAT_EXTERN(TEXT("Joints"), STAT_Box3DJoints, STATGROUP_Box3D, BOX3DUNREAL_API);
DECLARE_DWORD_COUNTER_STAT_EXTERN(TEXT("Islands"), STAT_Box3DIslands, STATGROUP_Box3D, BOX3DUNREAL_API);
DECLARE_DWORD_COUNTER_STAT_EXTERN(TEXT("Steps this frame"), STAT_Box3DStepsPerFrame, STATGROUP_Box3D, BOX3DUNREAL_API);
